# Header
menu:
  Home: /
  About: /about
  Gallery: /gallery
  Budva: /budva
  Guestbook: /guestbook
  Contact: /contact

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
